
/*

            uuuuuuuuuuuuuuuuuuuu
          u" uuuuuuuuuuuuuuuuuu "u
        u" u$$$$$$$$$$$$$$$$$$$$u "u
      u" u$$$$$$$$$$$$$$$$$$$$$$$$u "u
    u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
  u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
u" u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$u "u
$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
$ $$$" ... "$...  ...$" ... "$$$  ... "$$$ $
$ $$$u `"$$$$$$$  $$$  $$$$$  $$  $$$  $$$ $
$ $$$$$$uu "$$$$  $$$  $$$$$  $$  """ u$$$ $
$ $$$""$$$  $$$$  $$$u "$$$" u$$  $$$$$$$$ $
$ $$$$....,$$$$$..$$$$$....,$$$$..$$$$$$$$ $
$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $
"u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
  "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
    "u "$$$$$$$$$$$$$$$$$$$$$$$$$$$$" u"
      "u "$$$$$$$$$$$$$$$$$$$$$$$$" u"
        "u "$$$$$$$$$$$$$$$$$$$$" u"
          "u """""""""""""""""" u"
            """"""""""""""""""""



DO NOT EDIT THIS FILE. IT IS GENERATED AUTOMATICALLY.
YOUR CHANGES WILL BE LOST. INSTEAD, EDIT KSPConfigStructs.tt
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KerbalInterstellarTechnologies.FuelStorage
{
    public class KITCryostatConfig {
        private KITCryostat _KITCryostat;
        public KITCryostatConfig(KITCryostat p = null) {
            _KITCryostat = p;
        }
        
        private System.Boolean _previousPowerMet;
        public System.Boolean previousPowerMet {
            get {
                if (_KITCryostat == null) return _previousPowerMet;
                return _KITCryostat.previousPowerMet;
            }
            set {
                if (_KITCryostat == null) { _previousPowerMet = value; return; };
                _KITCryostat.previousPowerMet = value;
            }
        }
        // Field: Boolean previousPowerMet previousPowerMet 
        private System.String _resourceName;
        public System.String resourceName {
            get {
                if (_KITCryostat == null) return _resourceName;
                return _KITCryostat.resourceName;
            }
            set {
                if (_KITCryostat == null) { _resourceName = value; return; };
                _KITCryostat.resourceName = value;
            }
        }
        // Field: System.String resourceName resourceName 
        private System.String _resourceGUIName;
        public System.String resourceGUIName {
            get {
                if (_KITCryostat == null) return _resourceGUIName;
                return _KITCryostat.resourceGUIName;
            }
            set {
                if (_KITCryostat == null) { _resourceGUIName = value; return; };
                _KITCryostat.resourceGUIName = value;
            }
        }
        // Field: System.String resourceGUIName resourceGUIName 
        private System.Double _boilOffRate;
        public System.Double boilOffRate {
            get {
                if (_KITCryostat == null) return _boilOffRate;
                return _KITCryostat.boilOffRate;
            }
            set {
                if (_KITCryostat == null) { _boilOffRate = value; return; };
                _KITCryostat.boilOffRate = value;
            }
        }
        // Field: Double boilOffRate boilOffRate 
        private System.Double _powerReqKW;
        public System.Double powerReqKW {
            get {
                if (_KITCryostat == null) return _powerReqKW;
                return _KITCryostat.powerReqKW;
            }
            set {
                if (_KITCryostat == null) { _powerReqKW = value; return; };
                _KITCryostat.powerReqKW = value;
            }
        }
        // Field: Double powerReqKW powerReqKW 
        private System.Double _powerReqMult;
        public System.Double powerReqMult {
            get {
                if (_KITCryostat == null) return _powerReqMult;
                return _KITCryostat.powerReqMult;
            }
            set {
                if (_KITCryostat == null) { _powerReqMult = value; return; };
                _KITCryostat.powerReqMult = value;
            }
        }
        // Field: Double powerReqMult powerReqMult 
        private System.Double _boilOffMultiplier;
        public System.Double boilOffMultiplier {
            get {
                if (_KITCryostat == null) return _boilOffMultiplier;
                return _KITCryostat.boilOffMultiplier;
            }
            set {
                if (_KITCryostat == null) { _boilOffMultiplier = value; return; };
                _KITCryostat.boilOffMultiplier = value;
            }
        }
        // Field: Double boilOffMultiplier boilOffMultiplier 
        private System.Double _boilOffBase;
        public System.Double boilOffBase {
            get {
                if (_KITCryostat == null) return _boilOffBase;
                return _KITCryostat.boilOffBase;
            }
            set {
                if (_KITCryostat == null) { _boilOffBase = value; return; };
                _KITCryostat.boilOffBase = value;
            }
        }
        // Field: Double boilOffBase boilOffBase 
        private System.Double _boilOffAddition;
        public System.Double boilOffAddition {
            get {
                if (_KITCryostat == null) return _boilOffAddition;
                return _KITCryostat.boilOffAddition;
            }
            set {
                if (_KITCryostat == null) { _boilOffAddition = value; return; };
                _KITCryostat.boilOffAddition = value;
            }
        }
        // Field: Double boilOffAddition boilOffAddition 
        private System.Double _boilOffTemp;
        public System.Double boilOffTemp {
            get {
                if (_KITCryostat == null) return _boilOffTemp;
                return _KITCryostat.boilOffTemp;
            }
            set {
                if (_KITCryostat == null) { _boilOffTemp = value; return; };
                _KITCryostat.boilOffTemp = value;
            }
        }
        // Field: Double boilOffTemp boilOffTemp 
        private System.Double _convectionMod;
        public System.Double convectionMod {
            get {
                if (_KITCryostat == null) return _convectionMod;
                return _KITCryostat.convectionMod;
            }
            set {
                if (_KITCryostat == null) { _convectionMod = value; return; };
                _KITCryostat.convectionMod = value;
            }
        }
        // Field: Double convectionMod convectionMod 
        
    }
}

